Mdl = TreeBagger(NumTrees,...
			Training_Data,...
			Terrain_Types,...
			"Method", "classification",...
			"MaxNumSplits", NumSplits,...
			"NumPredictorsToSample", Num_Feats,...
			"OOBPredictorImportance", "on",...
			OOBPrediction = "on",...
			InBagFraction = In_Bag_Fraction); 
